## 3.2 CartPole 실행해 보기

In [2]:
# 구현에 사용할 패키지 임포트
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import gym


In [3]:
# 애니메이션을 만드는 함수
# 참고 URL http://nbviewer.jupyter.org/github/patrickmineault/xcorr-notebooks/blob/master/Render%20OpenAI%20gym%20as%20GIF.ipynb
from JSAnimation.IPython_display import display_animation
from matplotlib import animation
from IPython.display import display


def display_frames_as_gif(frames):
    """
    Displays a list of frames as a gif, with controls
    """
    plt.figure(figsize=(frames[0].shape[1]/72.0, frames[0].shape[0]/72.0),
               dpi=72)
    patch = plt.imshow(frames[0])
    plt.axis('off')

    def animate(i):
        patch.set_data(frames[i])

    anim = animation.FuncAnimation(plt.gcf(), animate, frames=len(frames),
                                   interval=50)

    anim.save('movie_cartpole.mp4')  # 주석 추가 : 애니메이션을 저장하는 부분
    display(display_animation(anim, default_mode='loop'))


In [6]:
# 수레를 무작위로 움직임

frames = []
env = gym.make('CartPole-v0')
observation = env.reset()  # 먼저 환경을 초기화해야 함

for step in range(0, 200):
    env.render()  # frames에 각 시각의 이미지를 추가한다
    action = np.random.choice(2)  # 0(수레를 왼쪽으로), 1(수레를 오른쪽으로) 두 가지 행동을 무작위로 취함
    observation, reward, done, info = env.step(action)  # action을 실행
    print(observation, reward, done, info)

# 주의: 실행했을 때 ipykernel_launcher.p... 라는 창이 나타날 수 있지만, 무시하면 된다

[-0.04759267  0.1780663  -0.00533035 -0.27262271] 1.0 False {}
[-0.04403134  0.3732639  -0.01078281 -0.56698207] 1.0 False {}
[-0.03656606  0.56853544 -0.02212245 -0.86304244] 1.0 False {}
[-0.02519535  0.37372155 -0.0393833  -0.57739658] 1.0 False {}
[-0.01772092  0.17917309 -0.05093123 -0.29737587] 1.0 False {}
[-0.01413746  0.37498268 -0.05687875 -0.6056767 ] 1.0 False {}
[-0.00663781  0.18070029 -0.06899228 -0.33143774] 1.0 False {}
[-0.0030238   0.376733   -0.07562103 -0.64505489] 1.0 False {}
[ 0.00451086  0.57282278 -0.08852213 -0.96056034] 1.0 False {}
[ 0.01596732  0.37899501 -0.10773334 -0.69694863] 1.0 False {}
[ 0.02354722  0.1855189  -0.12167231 -0.44002939] 1.0 False {}
[ 0.02725759 -0.00768993 -0.1304729  -0.18804218] 1.0 False {}
[ 0.02710379  0.18903389 -0.13423374 -0.51887012] 1.0 False {}
[ 0.03088447  0.38576493 -0.14461115 -0.85065835] 1.0 False {}
[ 0.03859977  0.5825313  -0.16162431 -1.18509478] 1.0 False {}
[ 0.0502504   0.38983176 -0.18532621 -0.94712352] 1.0 F

[  4.18266716   2.32504707 -13.20355157  -4.24203305] 0.0 True {}
[  4.2291681    2.51174718 -13.28839223  -4.64204067] 0.0 True {}
[  4.27940305   2.31609734 -13.38123304  -4.61610186] 0.0 True {}
[  4.32572499   2.49627115 -13.47355508  -5.01541578] 0.0 True {}
[  4.37565042   2.67108162 -13.5738634   -5.40853693] 0.0 True {}
[  4.42907205   2.4688816  -13.68203413  -5.49515584] 0.0 True {}
[  4.47844968   2.63348778 -13.79193725  -5.86776419] 0.0 True {}
[  4.53111944   2.79134034 -13.90929254  -6.22454653] 0.0 True {}
[  4.58694624   2.94231259 -14.03378347  -6.56210489] 0.0 True {}
[  4.6457925    2.7227692  -14.16502556  -6.82055001] 0.0 True {}
[  4.70024788   2.49829263 -14.30143656  -7.12381513] 0.0 True {}
[  4.75021373   2.26838513 -14.44391287  -7.4702531 ] 0.0 True {}
[  4.79558143   2.39880375 -14.59331793  -7.69145811] 0.0 True {}
[  4.84355751   2.528775   -14.74714709  -7.86952026] 0.0 True {}
[  4.89413301   2.28917476 -14.9045375   -8.31638305] 0.0 True {}
[  4.93991

In [7]:
env.close()

In [10]:
%reset

Once deleted, variables cannot be recovered. Proceed (y/[n])? y


In [11]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import gym

ENV = 'CartPole-v0'
NUM_DIZITIZED = 6

env = gym.make(ENV)
observation = env.reset()

In [12]:
def bins(clip_min, clip_max, num):
    return np.linspace(clip_min, clip_max, num + 1)[1 : -1]

In [13]:
def observation_state(observation):
    cart_pos, cart_v, pole_angle, pole_v = observation
    digitized = [
        np.digitize(cart_pos, bins = bins(-2.4, 2.4, NUM_DIZITIZED)),
        np.digitize(cart_v, bins = bins(-3.0, 3.0, NUM_DIZITIZED)),
        np.digitize(pole_angle, bins = bins(-0.5, 0.5, NUM_DIZITIZED)),
        np.digitize(pole_v, bins = bins(-2.0, 2.0, NUM_DIZITIZED)),
    ]
    return sum([x * (NUM_DIZITIZED**i) for i, x in enumerate(digitized)])